

adapters:
  out:
    database:
      sql:
        postgre:
          host: "127.0.0.1"
          port: 5432

          user: "postgres"
          password: "admin"
          database: "time_tracker"
