start_timeout: 5s
stop_timeout: 5s

log:
  name: time_tracker
  level: 0
  format: text
  console:
    enable: true
  file:
    enable: true
    name: actions.log
    dir:
      name: ./rot
    rotation:
      enable: true
      count: 5
      size_kb: 25000

adapters:
  in: 
    http:
      host: localhost
      port: 55554
      read_timeout: 5s
      write_timeout: 5s

  out:
    database:
      sql:
        postgre:
          host: "127.0.0.1"
          port: 5432
          user: "postgres"
          password: "admin"
          database: "time_tracker"
